### ISSUE TITLE
Используй массив с невеганскими ингредиентами

### ISSUE THREAD

**Issue by uzarsalan** [poleskoea/homework-evgeny_polesko#11]
https://github.com/poleskoea/homework-evgeny_polesko/blob/386cb8be6708d253d6a9e15724811b58ef1ea5ce/Array%20methods/arrayMethods.js#L67

Для расширяемости лучше сделать отдельный массив с ингредиентами, которые делают блюдо невегетарианским

**Comment by poleskoea** [comment]
Спасибо, сделал
