### ISSUE TITLE
Неочевидное использование функции

### ISSUE THREAD

**Issue by uzarsalan** [poleskoea/homework-evgeny_polesko#8]
В целом функция выполняет свою задачу, но результат ее работы неочевиден. Желательно так не делать. Функция не должна менять аргументы, лучше чтобы она возвращала результат ее выполнения. В данном случае это просто стоимость блюда.

Почему так? Часто бывает что функция находится в другом файле или далеко от места ее использования. В том виде, в котором ты ее используешь, невозможно понять что она делает, не заглядывая внутрь ее реализации.

Попробуй переделать ее так, чтобы был очевиден результат ее применения.

В чате мы обсуждали этот момент с Артёмом

https://github.com/poleskoea/homework-evgeny_polesko/blob/4d59b3c247e4c7bf3e6a93373d89cddddefc164e/Functions/functions.js#L12

**Comment by poleskoea** [comment]
Сделал так чтобы не меняла ничего внутри объекта, а возвращала результат. Заодно ради тренировки попробовал сделать класс.

**Comment by poleskoea** [comment]
Видимо, нужно было сразу закрыть, когда я внёс изменения и оставил первый коммент. Кто вообще обычно закрывает issue? Тот кто его получил и внёс изменения или тот кто его создал после проверки изменений?
